sudo: false
language: node_js

node_js:
  - 10 # use nodejs v10 LTS
cache: npm

script:
  - hexo clean
  - hexo g


after_script:
  - cd ./public
  - git init
  - git config user.name "huangshubi"  #修改name
  - git config user.email "1732565636@qq.com"  #修改email
  - git add .
  - git commit -m "代码是自动部署的"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages  #Travis_Token是在Travis中配置环境变量的名称

branches:
  only:
    - master 

env:
 global:
   - GH_REF: github.com/huangshubi/huangshubi.git  #设置GH_REF，注意更改yourname


